Fixes #8433 - non-apostrophed ('...') url with multiple params support in cURL import
postmanlabs/curl-to-postman pull request #48
Opened 2022-05-05 18:50 UTC by SahilChoudhary22

- Fixes https://github.com/postmanlabs/postman-app-support/issues/8843
- Added few more test cases to support regex changes.

2022-05-06 07:25 UTC, umeshp7 requested changes

2022-05-06 07:25 UTC, umeshp7 commented on test/conversion.test.js
> +        expect(result.output[0].type).to.equal('request');
The test has to expect the right information you are expecting inside the request as well. For eg. the url in this case.

2022-05-06 07:25 UTC, umeshp7 commented on assets/shell-quote.js
>  var BAREWORD = '(\\\\[\'"' + META + ']|[^\\s\'"' + META + '])+';
@SahilChoudhary22 This is an external asset that we have added to the module. We will have to be completely sure before we make any changes to it.

2022-05-06 07:25 UTC, umeshp7 commented on assets/shell-quote.js
>  var BAREWORD = '(\\\\[\'"' + META + ']|[^\\s\'"' + META + '])+';
@SahilChoudhary22 This is an external asset that we have added to the module. We will have to be completely sure before we make any changes to it.

2022-05-06 07:25 UTC, umeshp7 commented on test/conversion.test.js
> +        -H "x-features: FEATURE1_ENABLED" \\
We can remove some of the unwanted headers etc. here and use the smallest version which reproduces the issue.

2022-05-06 07:25 UTC, umeshp7 commented on test/conversion.test.js
> +        -H "x-features: FEATURE1_ENABLED" \\
We can remove some of the unwanted headers etc. here and use the smallest version which reproduces the issue.

2022-05-06 07:25 UTC, umeshp7 commented on assets/shell-quote.js
> +var HTTP_URL_MATCHER  = "http[^ ]+";
@SahilChoudhary22 can we check the shell-quote npm module, if there are any open issues around this or if there is any handling already for this?

2022-05-06 07:25 UTC, umeshp7 commented on assets/shell-quote.js
> +var HTTP_URL_MATCHER  = "http[^ ]+";
@SahilChoudhary22 can we check the shell-quote npm module, if there are any open issues around this or if there is any handling already for this?

2022-05-06 07:25 UTC, umeshp7 commented on assets/shell-quote.js
> +var HTTP_URL_MATCHER  = "http[^ ]+";
The url could simply be www.google.com?foo=bar&foo=baz or google.com?foo=bar&foo=baz and these cases aren't covered with this.

2022-05-09 10:45 UTC, SahilChoudhary22 commented
- Rolled back the changes in `assets/shell-quote.js` to avoid modification in an external library. 
- Made changes in `src/lib.js` and added cURL string preprocessing to handle incorrectly formed input.
- Compacted the test cases, removed unnecessary headers. Added some more assertions in each test for proper testing.

2022-05-09 11:20 UTC, umeshp7 commented on test/conversion.test.js
> +        "test.com/?bar=1&baz=2"`
let's add a test with more than 2 query params.

2022-05-09 11:36 UTC, umeshp7 commented on src/lib.js
> +        var cleanedCurlString = curlString.replace(multiParamUrlRegEx, `'${curlString.match(multiParamUrlRegEx)}'`),
Will single quotes always work?

2022-05-09 11:39 UTC, umeshp7 commented on src/lib.js
> +        const multiParamUrlRegEx = /[^ ]+\.[^ ]+&[^ ]+/gm;
What will happen if we have a URL like this > 
`https://postman-echo.com/get?foo1=bar1&` 

@SahilChoudhary22

2022-05-09 11:42 UTC, umeshp7 commented
We should add additional handling for trailing `&` in the URL which is not accounted for in the current regex.

2022-05-09 11:57 UTC, umeshp7 commented
We should safe check at `arg.startsWith('$')`. And throw appropriate errors where necessary. 

If this `&` is still encountered after the handling like:`curl https://postman-echo.com/post -d foo1=bar1&foo2=bar2` these are clearly invalid. Then we should respond with an error saying "Error parsing curl: <message>"

2022-05-09 15:36 UTC, umeshp7 commented on test/conversion.test.js
> +        -H "Content-Type: application/json" \\
Do we need all these headers?

2022-05-12 14:37 UTC, umeshp7 approved these changes

2022-05-12 14:38 UTC, umeshp7 commented
@SahilChoudhary22 Looks good to me. 
Let's merge this and we can test this one beta.

2022-05-16 07:02 UTC, merged