Changed regex to check for prefix space in url with query parameters for given curl string
postmanlabs/curl-to-postman pull request #51
Opened 2023-01-09 10:28 UTC by sairam459

… prefix space

2023-01-09 12:18 UTC, VShingala requested changes
@sairam459 Can we add test case that makes sure we're handling such cURLs with problems correctly?

2023-01-10 05:51 UTC, sairam459 commented
@VShingala i have added the test cases.

2023-01-10 06:29 UTC, VShingala approved these changes

2023-01-10 06:46 UTC, SahilChoudhary22 approved these changes
LGTM

2023-01-10 06:47 UTC, merged